spring.application.name=devops

#Configurações do banco de dados
spring.datasource.url=jdbc:postgressql://localhost:5432/devops_db
spring.datasource.username=postgres
spring.datasource.password=123456

#Atualização automatica do esquema do banco de dados
spring.jpa.hibernate.ddl-auto=update

#Mostrar as consultas SQL no console
spring.jpa.show-sql=true

#Não mostrar as formatações SQL
spring.jpa.properties.hibernate.format_sql=false

#Configurações da porta do servidor
server.port=8080
