spring.application.name=devops

#Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/devops_db
spring.datasource.username=postgres
spring.datasource.password=123456

#Atualização automatica do esquema do banco de dados
spring.jpa.hibernate.ddl-auto=update

#Mostrar as consultas SQL no console
spring.jpa.show-sql=true

#Não mostrar as formatações SQL
spring.jpa.properties.hibernate.format_sql=false

#Configurações da porta do servidor
server.port=8080


# Recuperação de senha por email via Resend
resend.api.key=re_g2fcozBE_APJy5hVj86mkr76HR51a6fiq
resend.api.url=${RESEND_API_URL:https://api.resend.com/emails}
app.base-url=${APP_BASE_URL:http://localhost:8080}
